# Generated by Django 3.1.4 on 2020-12-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('autore', models.TextField()),
                ('pub_date', models.DateField(verbose_name='data pubblicazione')),
                ('corpo', models.TextField()),
            ],
        ),
    ]
